### ISSUE TITLE
Firework Rockets - Autocrafter Can't Craft This Item 

### ISSUE THREAD

**Issue by dnyank1** [Aeltumn/automated_crafting#26] opened 2021-07-20 03:50 UTC
Describe the bug (enhancement?)

Inputting paper and gunpowder into autocrafter, firework rocket in item frame - toast message says "Autocrafter Can't Craft This Item "

Setup an autocrafter
Put 'firework rocket' in it.
get error message

Expected behavior
dispense fireworks

Version Information
1.17.1

**Comment by Aeltumn** [comment] 2021-07-30 20:51
Duplicate of #19

**Closed as completed by Aeltumn** 2021-07-30 20:51 UTC
Labels: duplicate
